# Generated by Django 5.0.7 on 2024-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_requirements_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirements",
            name="status",
            field=models.CharField(
                choices=[
                    ("ge", "GENERATED"),
                    ("pn", "PENDING"),
                    ("ac", "ACCEPTED"),
                    ("re", "RECEIVED"),
                    ("se", "SENT"),
                ],
                max_length=2,
            ),
        ),
    ]
