# Generated by Django 5.0.7 on 2024-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_requirements_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirements",
            name="victim_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
