# Generated by Django 5.0.7 on 2024-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_requirements_victim_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirements",
            name="current_location",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
