# Generated by Django 5.0.7 on 2024-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_requirements_current_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="temp_log_qr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="qrcode/")),
            ],
        ),
    ]
